Add Random to the counterpick CSS in ranked
project-slippi/slippi-ssbm-c pull request #6
Opened 2022-12-24 17:07 UTC by walz0

Adds a CSIcon with the Question material to the CharPickerDialog. Uses HSD_Randi to select a random character and proceeds with the normal character confirm logic.

![image](https://user-images.githubusercontent.com/30139718/209444735-3b14f648-0277-4996-9ba4-a3435049a3d4.png)

2022-12-24 17:29 UTC, rapito requested changes
I would also change the places where CKIND_GANONDORF is being used and replace with a new constant CKIND_LAST_INDEX or similar so you dont have to replace all the places on the code, just change the value of the constant.  

As it is right now it makes it hard to scale as too many changes are needed in different places.

2022-12-24 17:29 UTC, rapito commented on Components/CharPickerDialog.c
> +  cpd->state.char_selection_idx = HSD_Randi(26);
@walz0 could you make the 26 use a constant instead?

2022-12-24 17:29 UTC, rapito commented on Components/CharPickerDialog.c
> +    if (cpd->state.char_selection_idx == 26) { // Select random
@walz0 same as the previous comment but this would be a different named constant, something like CKIND_RANDOM

2022-12-24 19:03 UTC, walz0 commented on Components/CharPickerDialog.c
> +    if (cpd->state.char_selection_idx == 26) { // Select random
should be much more scalable / readable now, i added constants for random and last index and refactored every instance where i used CKIND_GANONDORF +1 or 26

2024-01-06 17:06 UTC, walz0 commented
@JLaferri bumping this for possible merge since its been approved for a while

2025-08-11 02:45 UTC, merged